version : '3.8'

services:
    db:
        image: mysql:8.0
        container_name: db_apitest_club
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3301:3306"
        env_file:
            - ./app/.env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        networks:
            backend-net:
                ipv4_address: 106.0.101.3
        volumes:
            - ./app:/var/www
    
    php:
        build:
          context: './docker/php'
        ports:
            - "8096:8092"
        container_name: php_apitest_club
        networks:
            backend-net:
                ipv4_address: 106.0.101.2
        volumes:
            - ./app:/var/www
        env_file:
            - ./app/.env
        environment:
            MAIL_FROM: ${MAIL_FROM}
        links:
            - db
        depends_on:
            - db

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8091:80'
        env_file:
            - ./app/.env
        volumes:
            - ./app:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - MAIL_FROM=${MAIL_FROM}
        depends_on:
            - php
            - db
        networks:
            backend-net:
                ipv4_address: 106.0.101.4
networks:
    backend-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 106.0.101.0/26